import React from "react";
import './PokemonCard.css'

export default function PokemonCard({ name, image, types, storePageData }) {
    const capitalName = name[0].toUpperCase() + name.slice(1)
    const typeName = types.map(item => item.type.name)

    // --This is a hack for some tailwind colors issue where sometimes, if the color classes are not typed fully there and are instead defined dynamically (like in a variable/object), it doesn't work. So this means the same style class needs to be explicitly defined somewhere inside the component
    // const json = {
    //     bgColor: {
    //         0: "bg-grass",
    //         1: "bg-bug",
    //         2: "bg-poison",
    //         3: "bg-rock",
    //         4: "bg-flying",
    //         5: "bg-water",
    //         6: "bg-steel",
    //         7: "bg-psychic",
    //         8: "bg-normal",
    //         9: "bg-ice",
    //         10: "bg-ground",
    //         11: "bg-ghost",
    //         12: "bg-fire",
    //         13: "bg-fairy",
    //         14: "bg-fighting",
    //         15: "bg-electric",
    //         16: "bg-dragon",
    //     },
    //     gradientColor: {
    //         bug: {
    //             0: "bg-gradient-to-r from-bug to-grass",
    //             1: "bg-gradient-to-r from-bug to-poison",
    //             2: "bg-gradient-to-r from-bug to-rock",
    //             3: "bg-gradient-to-r from-bug to-flying",
    //             4: "bg-gradient-to-r from-bug to-water",
    //             5: "bg-gradient-to-r from-bug to-steel",
    //             6: "bg-gradient-to-r from-bug to-psychic",
    //             7: "bg-gradient-to-r from-bug to-normal",
    //             8: "bg-gradient-to-r from-bug to-ice",
    //             9: "bg-gradient-to-r from-bug to-ground",
    //             10: "bg-gradient-to-r from-bug to-ghost",
    //             11: "bg-gradient-to-r from-bug to-fire",
    //             12: "bg-gradient-to-r from-bug to-fairy",
    //             13: "bg-gradient-to-r from-bug to-fighting",
    //             14: "bg-gradient-to-r from-bug to-electric",
    //             15: "bg-gradient-to-r from-bug to-dragon",
    //         },
    //         poison: {
    //             grass: "bg-gradient-to-r from-poison to-grass",
    //             bug: "bg-gradient-to-r from-poison to-bug",
    //             rock: "bg-gradient-to-r from-poison to-rock",
    //             flying: "bg-gradient-to-r from-poison to-flying",
    //             water: "bg-gradient-to-r from-poison to-water",
    //             steel: "bg-gradient-to-r from-poison to-steel",
    //             psychic: "bg-gradient-to-r from-poison to-psychic",
    //             normal: "bg-gradient-to-r from-poison to-normal",
    //             ice: "bg-gradient-to-r from-poison to-ice",
    //             ground: "bg-gradient-to-r from-poison to-ground",
    //             ghost: "bg-gradient-to-r from-poison to-ghost",
    //             fire: "bg-gradient-to-r from-poison to-fire",
    //             fairy: "bg-gradient-to-r from-poison to-fairy",
    //             fighting: "bg-gradient-to-r from-poison to-fighting",
    //             electric: "bg-gradient-to-r from-poison to-electric",
    //             dragon: "bg-gradient-to-r from-poison to-dragon",
    //           },
    //           rock: {
    //             grass: "bg-gradient-to-r from-rock to-grass",
    //             bug: "bg-gradient-to-r from-rock to-bug",
    //             poison: "bg-gradient-to-r from-rock to-poison",
    //             flying: "bg-gradient-to-r from-rock to-flying",
    //             water: "bg-gradient-to-r from-rock to-water",
    //             steel: "bg-gradient-to-r from-rock to-steel",
    //             psychic: "bg-gradient-to-r from-rock to-psychic",
    //             normal: "bg-gradient-to-r from-rock to-normal",
    //             ice: "bg-gradient-to-r from-rock to-ice",
    //             ground: "bg-gradient-to-r from-rock to-ground",
    //             ghost: "bg-gradient-to-r from-rock to-ghost",
    //             fire: "bg-gradient-to-r from-rock to-fire",
    //             fairy: "bg-gradient-to-r from-rock to-fairy",
    //             fighting: "bg-gradient-to-r from-rock to-fighting",
    //             electric: "bg-gradient-to-r from-rock to-electric",
    //             dragon: "bg-gradient-to-r from-rock to-dragon",
    //           },
    //           flying: {
    //             grass: "bg-gradient-to-r from-flying to-grass",
    //             bug: "bg-gradient-to-r from-flying to-bug",
    //             poison: "bg-gradient-to-r from-flying to-poison",
    //             rock: "bg-gradient-to-r from-flying to-rock",
    //             water: "bg-gradient-to-r from-flying to-water",
    //             steel: "bg-gradient-to-r from-flying to-steel",
    //             psychic: "bg-gradient-to-r from-flying to-psychic",
    //             normal: "bg-gradient-to-r from-flying to-normal",
    //             ice: "bg-gradient-to-r from-flying to-ice",
    //             ground: "bg-gradient-to-r from-flying to-ground",
    //             ghost: "bg-gradient-to-r from-flying to-ghost",
    //             fire: "bg-gradient-to-r from-flying to-fire",
    //             fairy: "bg-gradient-to-r from-flying to-fairy",
    //             fighting: "bg-gradient-to-r from-flying to-fighting",
    //             electric: "bg-gradient-to-r from-flying to-electric",
    //             dragon: "bg-gradient-to-r from-flying to-dragon",
    //           },
    //           water: {
    //             grass: "bg-gradient-to-r from-water to-grass",
    //             bug: "bg-gradient-to-r from-water to-bug",
    //             poison: "bg-gradient-to-r from-water to-poison",
    //             rock: "bg-gradient-to-r from-water to-rock",
    //             flying: "bg-gradient-to-r from-water to-flying",
    //             steel: "bg-gradient-to-r from-water to-steel",
    //             psychic: "bg-gradient-to-r from-water to-psychic",
    //             normal: "bg-gradient-to-r from-water to-normal",
    //             ice: "bg-gradient-to-r from-water to-ice",
    //             ground: "bg-gradient-to-r from-water to-ground",
    //             ghost: "bg-gradient-to-r from-water to-ghost",
    //             fire: "bg-gradient-to-r from-water to-fire",
    //             fairy: "bg-gradient-to-r from-water to-fairy",
    //             fighting: "bg-gradient-to-r from-water to-fighting",
    //             electric: "bg-gradient-to-r from-water to-electric",
    //             dragon: "bg-gradient-to-r from-water to-dragon",
    //           },
    //           steel: {
    //             grass: "bg-gradient-to-r from-steel to-grass",
    //             bug: "bg-gradient-to-r from-steel to-bug",
    //             poison: "bg-gradient-to-r from-steel to-poison",
    //             rock: "bg-gradient-to-r from-steel to-rock",
    //             flying: "bg-gradient-to-r from-steel to-flying",
    //             water: "bg-gradient-to-r from-steel to-water",
    //             psychic: "bg-gradient-to-r from-steel to-psychic",
    //             normal: "bg-gradient-to-r from-steel to-normal",
    //             ice: "bg-gradient-to-r from-steel to-ice",
    //             ground: "bg-gradient-to-r from-steel to-ground",
    //             ghost: "bg-gradient-to-r from-steel to-ghost",
    //             fire: "bg-gradient-to-r from-steel to-fire",
    //             fairy: "bg-gradient-to-r from-steel to-fairy",
    //             fighting: "bg-gradient-to-r from-steel to-fighting",
    //             electric: "bg-gradient-to-r from-steel to-electric",
    //             dragon: "bg-gradient-to-r from-steel to-dragon",
    //           },
    //           psychic: {
    //             grass: "bg-gradient-to-r from-psychic to-grass",
    //             bug: "bg-gradient-to-r from-psychic to-bug",
    //             poison: "bg-gradient-to-r from-psychic to-poison",
    //             rock: "bg-gradient-to-r from-psychic to-rock",
    //             flying: "bg-gradient-to-r from-psychic to-flying",
    //             water: "bg-gradient-to-r from-psychic to-water",
    //             steel: "bg-gradient-to-r from-psychic to-steel",
    //             normal: "bg-gradient-to-r from-psychic to-normal",
    //             ice: "bg-gradient-to-r from-psychic to-ice",
    //             ground: "bg-gradient-to-r from-psychic to-ground",
    //             ghost: "bg-gradient-to-r from-psychic to-ghost",
    //             fire: "bg-gradient-to-r from-psychic to-fire",
    //             fairy: "bg-gradient-to-r from-psychic to-fairy",
    //             fighting: "bg-gradient-to-r from-psychic to-fighting",
    //             electric: "bg-gradient-to-r from-psychic to-electric",
    //             dragon: "bg-gradient-to-r from-psychic to-dragon",
    //           },
    //           normal: {
    //             grass: "bg-gradient-to-r from-normal to-grass",
    //             bug: "bg-gradient-to-r from-normal to-bug",
    //             poison: "bg-gradient-to-r from-normal to-poison",
    //             rock: "bg-gradient-to-r from-normal to-rock",
    //             flying: "bg-gradient-to-r from-normal to-flying",
    //             water: "bg-gradient-to-r from-normal to-water",
    //             steel: "bg-gradient-to-r from-normal to-steel",
    //             psychic: "bg-gradient-to-r from-normal to-psychic",
    //             ice: "bg-gradient-to-r from-normal to-ice",
    //             ground: "bg-gradient-to-r from-normal to-ground",
    //             ghost: "bg-gradient-to-r from-normal to-ghost",
    //             fire: "bg-gradient-to-r from-normal to-fire",
    //             fairy: "bg-gradient-to-r from-normal to-fairy",
    //             fighting: "bg-gradient-to-r from-normal to-fighting",
    //             electric: "bg-gradient-to-r from-normal to-electric",
    //             dragon: "bg-gradient-to-r from-normal to-dragon",
    //           },
    //           ice: {
    //             grass: "bg-gradient-to-r from-ice to-grass",
    //             bug: "bg-gradient-to-r from-ice to-bug",
    //             poison: "bg-gradient-to-r from-ice to-poison",
    //             rock: "bg-gradient-to-r from-ice to-rock",
    //             flying: "bg-gradient-to-r from-ice to-flying",
    //             water: "bg-gradient-to-r from-ice to-water",
    //             steel: "bg-gradient-to-r from-ice to-steel",
    //             psychic: "bg-gradient-to-r from-ice to-psychic",
    //             normal: "bg-gradient-to-r from-ice to-normal",
    //             ground: "bg-gradient-to-r from-ice to-ground",
    //             ghost: "bg-gradient-to-r from-ice to-ghost",
    //             fire: "bg-gradient-to-r from-ice to-fire",
    //             fairy: "bg-gradient-to-r from-ice to-fairy",
    //             fighting: "bg-gradient-to-r from-ice to-fighting",
    //             electric: "bg-gradient-to-r from-ice to-electric",
    //             dragon: "bg-gradient-to-r from-ice to-dragon",
    //           },
    //           ground: {
    //             grass: "bg-gradient-to-r from-ground to-grass",
    //             bug: "bg-gradient-to-r from-ground to-bug",
    //             poison: "bg-gradient-to-r from-ground to-poison",
    //             rock: "bg-gradient-to-r from-ground to-rock",
    //             flying: "bg-gradient-to-r from-ground to-flying",
    //             water: "bg-gradient-to-r from-ground to-water",
    //             steel: "bg-gradient-to-r from-ground to-steel",
    //             psychic: "bg-gradient-to-r from-ground to-psychic",
    //             normal: "bg-gradient-to-r from-ground to-normal",
    //             ice: "bg-gradient-to-r from-ground to-ice",
    //             ghost: "bg-gradient-to-r from-ground to-ghost",
    //             fire: "bg-gradient-to-r from-ground to-fire",
    //             fairy: "bg-gradient-to-r from-ground to-fairy",
    //             fighting: "bg-gradient-to-r from-ground to-fighting",
    //             electric: "bg-gradient-to-r from-ground to-electric",
    //             dragon: "bg-gradient-to-r from-ground to-dragon",
    //           },
    //           ghost: {
    //             grass: "bg-gradient-to-r from-ghost to-grass",
    //             bug: "bg-gradient-to-r from-ghost to-bug",
    //             poison: "bg-gradient-to-r from-ghost to-poison",
    //             rock: "bg-gradient-to-r from-ghost to-rock",
    //             flying: "bg-gradient-to-r from-ghost to-flying",
    //             water: "bg-gradient-to-r from-ghost to-water",
    //             steel: "bg-gradient-to-r from-ghost to-steel",
    //             psychic: "bg-gradient-to-r from-ghost to-psychic",
    //             normal: "bg-gradient-to-r from-ghost to-normal",
    //             ice: "bg-gradient-to-r from-ghost to-ice",
    //             ground: "bg-gradient-to-r from-ghost to-ground",
    //             fire: "bg-gradient-to-r from-ghost to-fire",
    //             fairy: "bg-gradient-to-r from-ghost to-fairy",
    //             fighting: "bg-gradient-to-r from-ghost to-fighting",
    //             electric: "bg-gradient-to-r from-ghost to-electric",
    //             dragon: "bg-gradient-to-r from-ghost to-dragon",
    //           },
    //           fire: {
    //             grass: "bg-gradient-to-r from-fire to-grass",
    //             bug: "bg-gradient-to-r from-fire to-bug",
    //             poison: "bg-gradient-to-r from-fire to-poison",
    //             rock: "bg-gradient-to-r from-fire to-rock",
    //             flying: "bg-gradient-to-r from-fire to-flying",
    //             water: "bg-gradient-to-r from-fire to-water",
    //             steel: "bg-gradient-to-r from-fire to-steel",
    //             psychic: "bg-gradient-to-r from-fire to-psychic",
    //             normal: "bg-gradient-to-r from-fire to-normal",
    //             ice: "bg-gradient-to-r from-fire to-ice",
    //             ground: "bg-gradient-to-r from-fire to-ground",
    //             ghost: "bg-gradient-to-r from-fire to-ghost",
    //             fairy: "bg-gradient-to-r from-fire to-fairy",
    //             fighting: "bg-gradient-to-r from-fire to-fighting",
    //             electric: "bg-gradient-to-r from-fire to-electric",
    //             dragon: "bg-gradient-to-r from-fire to-dragon",
    //           },
    //           fairy: {
    //             grass: "bg-gradient-to-r from-fairy to-grass",
    //             bug: "bg-gradient-to-r from-fairy to-bug",
    //             poison: "bg-gradient-to-r from-fairy to-poison",
    //             rock: "bg-gradient-to-r from-fairy to-rock",
    //             flying: "bg-gradient-to-r from-fairy to-flying",
    //             water: "bg-gradient-to-r from-fairy to-water",
    //             steel: "bg-gradient-to-r from-fairy to-steel",
    //             psychic: "bg-gradient-to-r from-fairy to-psychic",
    //             normal: "bg-gradient-to-r from-fairy to-normal",
    //             ice: "bg-gradient-to-r from-fairy to-ice",
    //             ground: "bg-gradient-to-r from-fairy to-ground",
    //             ghost: "bg-gradient-to-r from-fairy to-ghost",
    //             fire: "bg-gradient-to-r from-fairy to-fire",
    //             fighting: "bg-gradient-to-r from-fairy to-fighting",
    //             electric: "bg-gradient-to-r from-fairy to-electric",
    //             dragon: "bg-gradient-to-r from-fairy to-dragon",
    //           },
    //           fighting: {
    //             grass: "bg-gradient-to-r from-fighting to-grass",
    //             bug: "bg-gradient-to-r from-fighting to-bug",
    //             poison: "bg-gradient-to-r from-fighting to-poison",
    //             rock: "bg-gradient-to-r from-fighting to-rock",
    //             flying: "bg-gradient-to-r from-fighting to-flying",
    //             water: "bg-gradient-to-r from-fighting to-water",
    //             steel: "bg-gradient-to-r from-fighting to-steel",
    //             psychic: "bg-gradient-to-r from-fighting to-psychic",
    //             normal: "bg-gradient-to-r from-fighting to-normal",
    //             ice: "bg-gradient-to-r from-fighting to-ice",
    //             ground: "bg-gradient-to-r from-fighting to-ground",
    //             ghost: "bg-gradient-to-r from-fighting to-ghost",
    //             fire: "bg-gradient-to-r from-fighting to-fire",
    //             fairy: "bg-gradient-to-r from-fighting to-fairy",
    //             electric: "bg-gradient-to-r from-fighting to-electric",
    //             dragon: "bg-gradient-to-r from-fighting to-dragon",
    //           },
              
    //           electric: {
    //             grass: "bg-gradient-to-r from-electric to-grass",
    //             bug: "bg-gradient-to-r from-electric to-bug",
    //             poison: "bg-gradient-to-r from-electric to-poison",
    //             rock: "bg-gradient-to-r from-electric to-rock",
    //             flying: "bg-gradient-to-r from-electric to-flying",
    //             water: "bg-gradient-to-r from-electric to-water",
    //             steel: "bg-gradient-to-r from-electric to-steel",
    //             psychic: "bg-gradient-to-r from-electric to-psychic",
    //             normal: "bg-gradient-to-r from-electric to-normal",
    //             ice: "bg-gradient-to-r from-electric to-ice",
    //             ground: "bg-gradient-to-r from-electric to-ground",
    //             ghost: "bg-gradient-to-r from-electric to-ghost",
    //             fire: "bg-gradient-to-r from-electric to-fire",
    //             fairy: "bg-gradient-to-r from-electric to-fairy",
    //             fighting: "bg-gradient-to-r from-electric to-fighting",
    //             dragon: "bg-gradient-to-r from-electric to-dragon",
    //           },
    //           dragon: {
    //             grass: "bg-gradient-to-r from-dragon to-grass",
    //             bug: "bg-gradient-to-r from-dragon to-bug",
    //             poison: "bg-gradient-to-r from-dragon to-poison",
    //             rock: "bg-gradient-to-r from-dragon to-rock",
    //             flying: "bg-gradient-to-r from-dragon to-flying",
    //             water: "bg-gradient-to-r from-dragon to-water",
    //             steel: "bg-gradient-to-r from-dragon to-steel",
    //             psychic: "bg-gradient-to-r from-dragon to-psychic",
    //             normal: "bg-gradient-to-r from-dragon to-normal",
    //             ice: "bg-gradient-to-r from-dragon to-ice",
    //             ground: "bg-gradient-to-r from-dragon to-ground",
    //             ghost: "bg-gradient-to-r from-dragon to-ghost",
    //             fire: "bg-gradient-to-r from-dragon to-fire",
    //             fairy: "bg-gradient-to-r from-dragon to-fairy",
    //             fighting: "bg-gradient-to-r from-dragon to-fighting",
    //             electric: "bg-gradient-to-r from-dragon to-electric",
    //           },
    //           grass: {
    //             dragon: "bg-gradient-to-r from-grass to-dragon",
    //             bug: "bg-gradient-to-r from-grass to-bug",
    //             poison: "bg-gradient-to-r from-grass to-poison",
    //             rock: "bg-gradient-to-r from-grass to-rock",
    //             flying: "bg-gradient-to-r from-grass to-flying",
    //             water: "bg-gradient-to-r from-grass to-water",
    //             steel: "bg-gradient-to-r from-grass to-steel",
    //             psychic: "bg-gradient-to-r from-grass to-psychic",
    //             normal: "bg-gradient-to-r from-grass to-normal",
    //             ice: "bg-gradient-to-r from-grass to-ice",
    //             ground: "bg-gradient-to-r from-grass to-ground",
    //             ghost: "bg-gradient-to-r from-grass to-ghost",
    //             fire: "bg-gradient-to-r from-grass to-fire",
    //             fairy: "bg-gradient-to-r from-grass to-fairy",
    //             fighting: "bg-gradient-to-r from-grass to-fighting",
    //             electric: "bg-gradient-to-r from-grass to-electric",
    //           },
    //     }
    // }
  
    return (
        <>
            <div className="bg-white rounded-lg shadow-md overflow-hidden w-52 max-w-xs" onClick={storePageData}>
                <div className=''>
                    <div className={`${typeName[1] ? `bg-gradient-to-r from-${typeName[0]} to-${typeName[1]}` : `bg-${typeName[0]}`}`}>

                        <img className="w-full h-36 mx-auto lg:w-1/2" src={image} />
                    </div>
                </div>
                <div className="p-4">
                    <h2 className="text-lg text-center font-medium text-gray-800">{capitalName}</h2>
                    <div className="mt-2 text-sm text-gray-600">
                    </div>
                    <div className="flex mx-8 mt-4 md:mt-0 ">
                        {typeName.map((type, index) => (
                            <div className={`icon ${type}`} key={index}>
                                <img src={`/assets/icons/${type}.svg`} alt={type} className="" />
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </>
    )
}

